name: Build and Push Images to AWS ECR

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    # Only trigger when these paths change
    paths:
      - 'src/**'
      - 'Dockerfile*'
      - '**/Dockerfile*'
      - 'package*.json'
      - 'requirements*.txt'
      - 'go.*'
      - '**/go.*'
      - '**/*.go'
      - '**/*.js'
      - '**/*.py'
      - '**/*.sh'
      - '.github/workflows/build.yml'

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY_WEBAPP: redis-pubsub-101/webapp
  ECR_REPOSITORY_CONTROLLER: redis-pubsub-101/controller
  ECR_REPOSITORY_SCHEDULER: redis-pubsub-101/scheduler

jobs:
  build:
    name: Build and Push Images to AWS ECR
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write   # required for OIDC token request
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::838835070561:role/github_actions_redis_pubpub_101
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push images to Amazon ECR
      id: build-images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_WEBAPP:$IMAGE_TAG -f src/app/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_WEBAPP:$IMAGE_TAG

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_CONTROLLER:$IMAGE_TAG -f src/controller/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_CONTROLLER:$IMAGE_TAG

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_SCHEDULER:$IMAGE_TAG -f src/scheduler/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_SCHEDULER:$IMAGE_TAG

    - name: Save Image Tag
      run: |
        mkdir -p artifacts
        echo ${{ github.ref_name }}-${{ github.sha }} > artifacts/image_tag.txt

    - name: Upload Image Tag Artifact
      uses: actions/upload-artifact@v4
      with:
        name: image-tag
        path: artifacts/image_tag.txt
